// src/pages/Terms.jsx — Terms of Service. Solicitor-reviewed 11 August 2026.
//
// Deliberately conservative: it does not promise uptime, does not claim
// compliance certifications, and does not overstate what the AI does. Those
// limits come from CLAUDE.md's marketing-accuracy rules, which apply here
// because this is a public page a customer can rely on. Changes here went
// through legal review once already — a substantive edit should go back
// through it again, not just get merged.
import React from 'react';
import LegalPage, { Section } from '@components/legal/LegalPage';
import { SALES_EMAIL } from '@components/landing/links';

export default function Terms() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="11 August 2026">
      <p>
        These terms govern use of ASOS. By creating an account you agree to them. If you are
        agreeing on behalf of a company, you confirm you are authorised to bind it.
      </p>

      <Section heading="The service">
        <p>
          ASOS connects to your WhatsApp Business number and uses AI agents to qualify
          inbound leads and draft replies. Accounts require approval before first sign-in.
          We may change or discontinue features; we will give reasonable notice of material
          reductions where we can.
        </p>
      </Section>

      <Section heading="Your responsibilities">
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>You are responsible for every message sent from your number</strong>,
            including AI-generated ones. Review your AI configuration before enabling
            automatic replies.
          </li>
          <li>
            You must have a lawful basis to message the people you contact, and must comply
            with WhatsApp Business Platform policy, Meta&rsquo;s terms, and any anti-spam or
            marketing-consent law that applies to you.
          </li>
          <li>You must tell the people who message you that their conversation is handled with AI assistance, where the law requires it.</li>
          <li>You are responsible for keeping your credentials secure and for activity under your account.</li>
          <li>You must not use ASOS for unlawful, deceptive, or harassing messaging, or to send content you have no right to send.</li>
        </ul>
      </Section>

      <Section heading="AI output">
        <p>
          Replies are generated by machine learning models and{' '}
          <strong>may be inaccurate, incomplete, or inappropriate for a given conversation</strong>.
          The system instructs the model not to state facts absent from your configuration and
          applies a post-generation check, but this is a mitigation and not a guarantee.
          Treat AI output as a draft you are accountable for, not as advice.
        </p>
        <p>
          Lead scores, stages, and intent labels are machine inferences. Do not use them as
          the sole basis for a decision that materially affects someone.
        </p>
      </Section>

      <Section heading="Plans, billing and trials">
        <p>
          Paid plans are billed through Stripe on a recurring basis until cancelled. Trials
          convert to paid unless cancelled before the trial ends. Plan limits include AI token
          usage; exceeding them may pause AI processing until the next period or an upgrade.
          Fees already paid are non-refundable except where the law requires otherwise.
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          The service is provided on an <strong>&ldquo;as available&rdquo;</strong> basis.{' '}
          <strong>We do not offer an uptime guarantee or a service level agreement.</strong>{' '}
          ASOS depends on third parties — Meta, OpenAI, Stripe and our hosting providers — and
          an outage at any of them can interrupt the service.
        </p>
      </Section>

      <Section heading="Data">
        <p>
          Our handling of personal data is described in the{' '}
          <a className="text-indigo-400 hover:text-indigo-300 underline" href="/privacy">Privacy Policy</a>.
          You retain ownership of your data. You grant us the licence needed to operate the
          service, including sending message content to the AI providers listed there.
        </p>
      </Section>

      <Section heading="Suspension and termination">
        <p>
          You may close your account at any time. We may suspend or terminate an account that
          breaches these terms, poses a security or legal risk, or has unpaid fees. On
          termination, access ends; see the Privacy Policy for what happens to stored data.
        </p>
      </Section>

      <Section heading="Liability">
        <p>
          To the maximum extent the law allows, ASOS is not liable for indirect, incidental,
          or consequential loss, including lost profits, lost business, or lost data. Our
          total aggregate liability is limited to the fees you paid in the twelve months
          before the claim. Nothing here excludes liability that cannot lawfully be excluded.
        </p>
      </Section>

      <Section heading="Changes">
        <p>
          We may update these terms. Material changes will be notified by email or in the
          dashboard. Continuing to use ASOS after a change means you accept the revised terms.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          <a className="text-indigo-400 hover:text-indigo-300 underline" href={`mailto:${SALES_EMAIL}`}>{SALES_EMAIL}</a>
        </p>
        <p className="text-sm text-slate-500">
          Governing law and jurisdiction are intentionally left blank — your solicitor should
          set these to match where your business is registered.
        </p>
      </Section>
    </LegalPage>
  );
}
